apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  ports:
    - port: 8000
  selector:
    app: django
    tier: frontend
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: frontend
    spec:
      containers:
        - image: django-app:latest
          imagePullPolicy: Never
          name: app
          env:
            - name: DB_HOST
              value: django-postgres
            - name: DB_NAME
              value: appdb
            - name: DB_USER
              value: myuser
            - name: SECRET_KEY
              value: samplesecretkey123
            - name: ALLOWED_HOSTS
              value: '127.0.0.1'
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          ports:
            - containerPort: 8080
              name: app
          volumeMounts:
            - name: django-persistent-storage
              mountPath: /vol/web
        - image: proxy:latest
          imagePullPolicy: Never
          name: proxy
          env:
            - name: APP_HOST
              value: '127.0.0.1'
            - name: APP_PORT
              value: '8080'
          ports:
            - containerPort: 8000
              name: proxy
          volumeMounts:
            - name: django-persistent-storage
              mountPath: /vol/web
      volumes:
        - name: django-persistent-storage
          persistentVolumeClaim:
            claimName: django-pvc
