apiVersion: v1
kind: Service
metadata:
  name: django-postgres
  labels:
    app: django
spec:
  ports:
    - port: 5432
  selector:
    app: django
    tier: postgres
  clusterIP: None

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-postgres-pvc
  labels:
    app: django
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: linode-block-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-postgres
  labels:
    app: django
spec:
  selector:
    matchLabels:
      app: django
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: postgres
    spec:
      containers:
        - image: postgres:15.2
          name: postgres
          env:
            - name: POSTGRES_DB
              value: appdb
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
          ports:
            - containerPort: 5432
              name: postgres

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: django-postgres-pvc
